# Pandas passo a passo — Excel — tratar células vazias

Arquivo: **academia_nulos.xlsx**, aba **Alunos**. Cada linha representa um aluno fictício. mensalidade está em reais; visitas é o número de visitas registradas na semana.

## Abrir o arquivo

No Colab: na barra esquerda, clique na pasta Arquivos e no botão de upload. Envie o arquivo de dados indicado abaixo. No VS Code: coloque o arquivo na mesma pasta do notebook e abra essa pasta como projeto.

Se surgir `FileNotFoundError`, confira nome e pasta. No Colab, os arquivos enviados podem desaparecer ao encerrar a sessão; envie novamente quando necessário.

Não execute todos os notebooks juntos: cada atividade usa sua própria variável `df`.

O formato `.xlsx` é o Excel atual; `.xls` é um formato antigo. `pd.read_excel()` pode ler ambos, mas pode precisar de bibliotecas diferentes. Para este `.xlsx`, se faltar a dependência, execute `%pip install openpyxl` em uma célula e tente a leitura novamente.

**Conceito novo:** tratar ausências exige escolher uma regra. Neste exercício, substituímos somente o plano vazio por uma indicação de ausência. Não inventaremos mensalidade nem frequência. Preservaremos a tabela original.

## Como usar

1. Na primeira parte, tente resolver sem olhar o gabarito.
2. Escreva o código nas células de código e suas explicações nas células de texto.
3. Execute as células de cima para baixo.

**Como pensar:** qual informação preciso? Qual coluna contém essa informação? Quero todas as linhas ou apenas algumas? Qual operação responde à pergunta?

Comentários iniciados por `#` não são executados. `NameError` pode indicar uma preparação não executada; `KeyError` pode indicar um nome de coluna escrito incorretamente.

## Preparação

`import pandas as pd` disponibiliza a biblioteca com o apelido `pd`. A função de leitura abre o arquivo e cria um DataFrame. `df =` guarda a tabela na variável `df`. O arquivo precisa estar na pasta de trabalho; o notebook não cria o arquivo de entrada.

Os números à esquerda são os índices das linhas. Eles começam em zero.

In [41]:
import pandas as pd

df = pd.read_excel("academia_nulos.xlsx", sheet_name="Alunos")
df

    aluno   plano  mensalidade  visitas
0     Ana  Mensal        120.0      3.0
1   Bruno     NaN        100.0      1.0
2   Carla  Mensal          NaN      4.0
3   Diego   Anual         80.0      NaN
4   Elisa   Anual         80.0      5.0
5  Felipe  Mensal        120.0      0.0

## Parte 1 — perguntas

Para cada questão: **preveja → escreva → execute → interprete**.

### Questão 1

Mostre as primeiras linhas e o tamanho da tabela.

**Pense antes:** A aba tem quantos alunos?

**Minha previsão:**

Escreva aqui.

In [42]:
# Escreva sua solução abaixo.

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 2

Inspecione tipos e valores preenchidos.

**Pense antes:** Quais colunas têm ausências?

**Minha previsão:**

Escreva aqui.

In [43]:
# Escreva sua solução abaixo.

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 3

Mostre nome e mensalidade dos alunos usando loc.

**Pense antes:** Como selecionar duas colunas?

**Minha previsão:**

Escreva aqui.

In [44]:
# Escreva sua solução abaixo.

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 4

Calcule a média das mensalidades conhecidas.

**Pense antes:** Qual aluno fica fora desse cálculo?

**Minha previsão:**

Escreva aqui.

In [45]:
# Escreva sua solução abaixo.

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 5

Crie uma cópia e preencha apenas o plano vazio com Não informado.

**Pense antes:** Preencher o plano altera a mensalidade?

**Minha previsão:**

Escreva aqui.

In [46]:
# Escreva sua solução abaixo.

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 6

Crie uma tabela só com mensalidades registradas.

**Pense antes:** Estamos removendo a linha da original?

**Minha previsão:**

Escreva aqui.

In [47]:
# Escreva sua solução abaixo.

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 7

Mostre quem precisa de conferência porque não tem mensalidade.

**Pense antes:** Como evitar perder de vista os dados incompletos?

**Minha previsão:**

Escreva aqui.

In [48]:
# Escreva sua solução abaixo.

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 8

Compare ausência de visitas com zero visitas.

**Pense antes:** Podemos preencher a visita desconhecida com zero sem confirmar?

**Minha previsão:**

Escreva aqui.

In [49]:
# Escreva sua solução abaixo.

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 9

Exporte a tabela tratada para CSV.

**Pense antes:** Por que usar index=False?

**Minha previsão:**

Escreva aqui.

In [50]:
# Escreva sua solução abaixo.

**Minha interpretação do resultado:**

Escreva aqui.

## Parte 2 — resolução comentada

Compare com suas tentativas. Leia como pensar, execute o código e explique o resultado com suas palavras. Comece executando a preparação novamente.

In [51]:
import pandas as pd

df = pd.read_excel("academia_nulos.xlsx", sheet_name="Alunos")
df

    aluno   plano  mensalidade  visitas
0     Ana  Mensal        120.0      3.0
1   Bruno     NaN        100.0      1.0
2   Carla  Mensal          NaN      4.0
3   Diego   Anual         80.0      NaN
4   Elisa   Anual         80.0      5.0
5  Felipe  Mensal        120.0      0.0

### Resolução 1

**Pedido:** Mostre as primeiras linhas e o tamanho da tabela.

**Como pensar:** Lemos a aba indicada e fazemos uma inspeção inicial.

In [52]:
print(df.shape)
df.head()

(6, 4)

   aluno   plano  mensalidade  visitas
0    Ana  Mensal        120.0      3.0
1  Bruno     NaN        100.0      1.0
2  Carla  Mensal          NaN      4.0
3  Diego   Anual         80.0      NaN
4  Elisa   Anual         80.0      5.0

**Resultado explicado:** 6 alunos, 4 colunas; head mostra os cinco primeiros.

### Resolução 2

**Pedido:** Inspecione tipos e valores preenchidos.

**Como pensar:** info resume os tipos e contagens; isna().sum conta ausências.

In [53]:
df.info()
print(df.isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   aluno        6 non-null      object
 1   plano        5 non-null      object
 2   mensalidade  5 non-null      float64
 3   visitas      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 320.0+ bytes
aluno          0
plano          1
mensalidade    1
visitas        1
dtype: int64

**Resultado explicado:** plano, mensalidade e visitas têm uma ausência cada.

### Resolução 3

**Pedido:** Mostre nome e mensalidade dos alunos usando loc.

**Como pensar:** Usamos : para todas as linhas e uma lista para duas colunas.

In [54]:
df.loc[:, ["aluno", "mensalidade"]]

    aluno  mensalidade
0     Ana        120.0
1   Bruno        100.0
2   Carla          NaN
3   Diego         80.0
4   Elisa         80.0
5  Felipe        120.0

**Resultado explicado:** A mensalidade de Carla está ausente.

### Resolução 4

**Pedido:** Calcule a média das mensalidades conhecidas.

**Como pensar:** mean ignora a mensalidade ausente.

In [55]:
df["mensalidade"].mean()

np.float64(100.0)

**Resultado explicado:** A média dos cinco valores conhecidos é 100. Carla não participa do cálculo.

### Resolução 5

**Pedido:** Crie uma cópia e preencha apenas o plano vazio com Não informado.

**Como pensar:** copy preserva a original. fillna substitui ausências apenas na coluna escolhida.

In [56]:
df_tratado = df.copy()
df_tratado["plano"] = df_tratado["plano"].fillna("Não informado")
df_tratado

    aluno          plano  mensalidade  visitas
0     Ana         Mensal        120.0      3.0
1   Bruno  Não informado        100.0      1.0
2   Carla         Mensal          NaN      4.0
3   Diego          Anual         80.0      NaN
4   Elisa          Anual         80.0      5.0
5  Felipe         Mensal        120.0      0.0

**Resultado explicado:** Bruno passa a ter plano Não informado. As ausências numéricas continuam.

### Resolução 6

**Pedido:** Crie uma tabela só com mensalidades registradas.

**Como pensar:** dropna com subset considera só mensalidade. O resultado é guardado em outra variável.

In [57]:
df_com_mensalidade = df_tratado.dropna(subset=["mensalidade"])
df_com_mensalidade

    aluno          plano  mensalidade  visitas
0     Ana         Mensal        120.0      3.0
1   Bruno  Não informado        100.0      1.0
3   Diego          Anual         80.0      NaN
4   Elisa          Anual         80.0      5.0
5  Felipe         Mensal        120.0      0.0

**Resultado explicado:** A tabela resultante tem 5 alunos e exclui Carla. A original tem 6. Diego continua mesmo com visitas ausentes.

### Resolução 7

**Pedido:** Mostre quem precisa de conferência porque não tem mensalidade.

**Como pensar:** Filtramos a ausência para saber quais registros precisam de atualização.

In [58]:
df_tratado.loc[df_tratado["mensalidade"].isna(), ["aluno", "mensalidade"]]

   aluno  mensalidade
2  Carla          NaN

**Resultado explicado:** Carla precisa de conferência; ausência não significa que ela não paga.

### Resolução 8

**Pedido:** Compare ausência de visitas com zero visitas.

**Como pensar:** Separar ausência e zero conserva o significado do dado.

In [59]:
print(df_tratado.loc[df_tratado["visitas"].isna(), "aluno"])
print(df_tratado.loc[df_tratado["visitas"] == 0, "aluno"])

3    Diego
Name: aluno, dtype: object
5    Felipe
Name: aluno, dtype: object

**Resultado explicado:** Diego tem visitas desconhecidas. Felipe tem zero visitas registradas. Não temos justificativa para substituir a ausência por zero.

### Resolução 9

**Pedido:** Exporte a tabela tratada para CSV.

**Como pensar:** to_csv escreve um arquivo. index=False impede criar uma coluna extra com o índice.

In [60]:
df_tratado.to_csv("academia_tratada.csv", index=False, encoding="utf-8")

**Resultado explicado:** Um novo CSV é criado na pasta de trabalho. O Excel de entrada permanece igual. No Colab, clique com o botão direito no CSV gerado e escolha baixar.

## Lembretes

| Recurso | Significado |
|---|---|
| `df["coluna"]` | Seleciona uma coluna |
| `df[condicao]` | Seleciona as linhas que atendem à condição |
| `df.loc[linhas, colunas]` | Seleciona por rótulos ou condições |
| `df.iloc[linhas, colunas]` | Seleciona por posições começando em zero |
| `:` sozinho | Todas as linhas ou colunas |
| `0:3` no iloc | Posições 0, 1 e 2; exclui a posição 3 |
| `==` | Compara valores |
| `=` | Atribui um valor |

Selecionar ou mostrar um resultado não significa apagar as outras informações. A alteração de valores é feita explicitamente, como na questão 9.

Documentação: https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html